version: '3.7'

services:
  badger-db:
    image: icebaker/badger-db:0.0.1
    environment:
      BADGER_DB_DATA_PATH: /badger-db/data
      BADGER_DB_CONTEXT: my-service-name
      BADGER_DB_HOST: 0.0.0.0
      BADGER_DB_PORT: 9708
    volumes:
      - ./data/badger-db:/badger-db/data
    ports:
      - 9708:9708
